name: tasty-glitter
version: 0.1.0
synopsis: A git-based tasty golden test
maintainer: Christian Gram Kalhauge <christiankalhauge@gmail.com>
category: Testing

ghc-options: -Wall -fno-warn-incomplete-uni-patterns 

dependencies:
  - base >= 4.9 && < 5
  - attoparsec
  - bytestring
  - directory
  - filepath
  - tasty
  - HUnit
  - text
  - tagged
  - hspec-expectations-pretty-diff
  - typed-process

library:
  source-dirs: src

tests:
  tasty-glitter-test: 
    source-dirs: test/src
    main: Main.hs
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-glitter
      - hspec-expectations-pretty-diff

